# Generated by Django 4.1 on 2022-08-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commenting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentor',
            new_name='commenter',
        ),
    ]
