# Generated by Django 4.1 on 2022-08-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketing', '0002_alter_ticket_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_taken',
            field=models.DurationField(null=True),
        ),
    ]
